### ISSUE TITLE
안녕하세요, sapa 공부 시작 중입니다..^^;

### ISSUE THREAD

**Issue by arahansa** [easylogic/sapa#15]
안녕하세요.
js, canvas 등을 좀 심도 있게 파보고 싶어서, sapa 를 좀 봐보려고 하는데요~ 
공부해보고 클래스 같은 곳들에 주석 달아본 것을 jsdoc 처리를 해도 될까요?^^
(흠 아니면.. fork 된 곳에 주석을..+ㅂ+ 달아볼지.. )
오픈소스가 처음인 심봉사입니다 ㅠ 잘 부탁드립니다 ㅠㅅㅠ

https://jsdoc.app/about-getting-started.html

**Comment by easylogic** [comment]
우와 완전 환영합니다^^ 완전 좋아요
