### ISSUE TITLE
expectMethod 객체 리터럴에서의 중복된 속성 제거

### ISSUE THREAD

**Issue by arahansa** [easylogic/sapa#16]
expectMethod  객체 리터럴에서의 
중복된 속성 ( constructor, destroy, refresh ) 등이 나타나서 다음의 속성들을 제거하려고 합니다.

오픈소스에서의 깃 정책을 잘 모르고 오픈소스 풀리퀘 경험도 없다보니...^^; 
제 쪽의 fork 된 리포지토리에 우선 브랜치를 생성해서 풀리퀘스트를 해보겠습니다.. ㅎ

![image](https://user-images.githubusercontent.com/6437210/95654292-14ce3880-0b3a-11eb-8098-f44ff4fbdeba.png)

**Comment by easylogic** [comment]
감사합니다. ^^   

그걸 고치긴 해야 하는데 깜빡 하고 있었네요. 

사실 이 부분은 아예 조금 다르게 설계해볼까 하고 있었습니다.   
expectMethod 를 체크 하는 이유가  상위 Class 에 있는 메소드들을 모두 조회할 때  클래스가 정의하는 메소드는 제외 시킬려고 한 부분이라 .

그렇게 한 이유는  Sapa 의 메세징 시스템 때문에 그런데요. 

DOM Event  와 Store 기반의 Event 를 설정하기 위해서  특수한 메소드를 사용 하고 있는데 ,  상속 관계에서도 여전히 정의가 되어야 해서  상위 메소드를 모두 필터링 하는 것을 했었습니다. 

차후에는   전체 메소드를 필터링 하는게 아니라   특수 메소드에 대한 정의를 하고 그것만 필터링을 할려고 했어요. 

그렇게 되면 expectMethod 가 따로 정의가 되지 않아도 되는 부분이 있어서 설계를 잡아 보고 있습니다. ^^

**Comment by easylogic** [comment]
그리고 저는 따로 PR 에 대한 규칙이나 정책은 없습니다. (제가 룰을 좀 안 좋아하기도 하고, 좀 더 편안하게 코딩을 해보자는 의미로 그렇습니다. ^^)

관심 가져주신 것만으로도 좋은 것이라 ^^ 마음 껏 하셔도 될 것 같습니다.

**Comment by arahansa** [comment]
@easylogic 헛 넵 감사합니다. 
기능에 대한 개발은 제가 소스를 익히기 전까지는 당분간 힘들 것같고, 
제가 요새 막~~ eslint 의 세계를 알아서 lint 를 적용해볼까했는데, (룰을 좀 안 좋아한다고하셔서..흠.. ) 혹시 lint 는 어떠실까요? 'ㅁ';
아니면 기능 파악 해두면서 jsdoc 을 적어볼까하였습니다.

1) 가벼운 eslint 설정?
2) jsdoc
에서 선택지를 주시면 그 쪽 방향으로 좀 고민해보겠습니다^^;

**Comment by easylogic** [comment]
좋은 의견 주셔서 감사합니다. 

^^ lint 도 좋습니다. 
저도 필요할 때마다 jsdoc 은 계속 추가를 해야할 것 같습니다. 

js 프로젝트다 보니 vscode 지원이 조금 애매한 부분이 있어서 jsdoc 이 확실히 필요 한 것 같습니다.

**Comment by arahansa** [comment]
넵 감사합니다^^
