### ISSUE TITLE
매직 메서드의 재구성 

### ISSUE THREAD

**Issue by easylogic** [easylogic/sapa#18]
현재 Sapa 에서는 몇가지 매직메서드를 사용하고 있습니다.   

메소드 이름을 특정 행동으로 사용하는 패턴인데요.  보통은 Decorator 를 쓰는데  Sapa 에서는 매직메서드 라고 불리우고(?) 있습니다. 

이런 메소드의 종류가 몇가지 있습니다. 

* [BIND()]  - 특정 Dom 속성 바인딩을 위한 함수 
* [LOAD()]  - 특정 Dom 에  하위 HTML 을 바인딩을 하기 위한 함수 
* [EVENT()] - store 기반 이벤트  트리거 함수 
* [CLICK() ..... ] - CLICK, KEYDOWN  등의 DOM 이벤트 핸들링 함수 

내부적으로 보면  domevent, me@, load , bind  은 prefix 의 이름을 가진 함수들입니다.  

다만 현재는 초기 설계가 다 다르게 동작하도록 되어 있다 보니  하나의 행동을 묶을 수 없는 상태가 되어 버려서  구조를 개선할까 합니다. 

메소드 정의 하는 방법은 같고 내부 정의 로직만 다르게 갈 예정입니다. 

예를 들어 

```js
// before 
[CLICK()] ->  'domevent click $el'  
```
형태로 변환이 됐다면 

```js
//after
[CLICK()] -> '@magicmethod:domevent click $el' 
```

형태로 정의될 예정입니다. 

상속관계에서  @magicmethod 를 모두 조회해서  정의된 모듈에서 사용할 예정입니다. 

이렇게 되면 많은 곳에서 리팩토링이 이루어 질 수 있어서 코어코드를 좀 더 편하게 구현 할 수 있을 것으로 예상합니다.

**Comment by uznam8x** [comment]
@mg:click 은 어떤가요??

**Comment by easylogic** [comment]
@uznam8x  좋은 생각입니다. 

다만 저 위에도 적혀 있듯이  @mg 는 확장된 메소드(매직 메소드) 를 위한 prefix 라서  중간 다른 모듈로 분류할 구분자가 하나 더 필요합니다.
