### ISSUE TITLE
Create JSdoc configuration

### ISSUE THREAD

**Issue by arahansa** [easylogic/sapa#19]
I can't contribute sapa feature now yet.

But I think I can contribute documentation with jsdoc writing comment of function, learning of function roles. 

I will use jsdoc  ( https://jsdoc.app/  ), and make pull request someday.
I create this issue for creating feature number ^^.

## KR 
당장의 기능에 기여할 수는 없지만
기능들을 좀 파악해보면서 주석을 달아보며,  문서화에 기여를 할 수 있을 것같다는 생각에 
jsdoc 을 사용해서 설정을 잡고 풀리퀘를 해볼 예정입니다.

제쪽의 feature 브랜치 번호를 만들기 위하여 다음의 이슈를 남겨봅니다^^

**Comment by arahansa** [comment]
문서화 추가 플러그인의 고민

jsdoc 여러 템플릿들이 있었는데
https://github.com/jsdoc/jsdoc#templates

가장 최근까지 깃커밋내역이 있어보이고 디자인이 좋아보이는 better-docs 로 결정합니다^^;

**Comment by easylogic** [comment]
저도 그게 제일 괜찮은 것 같아요. ^^
