### ISSUE TITLE
탕자(?)의 귀환

### ISSUE THREAD

**Issue by arahansa** [easylogic/sapa#24]
흠 안녕하세요^^, 작년 10월 이후의 재등장이로군요.. 
제가 작년10월경에 사실 소속을 좀 옮긴(?)일이 있어서
당장 필요한 기술 스택 공부하고, 중간에 지인이 만들어달란 것도 있어서 그거 좀 만들고, 
올초에는 제가 어떤 애니송 가수분 팬이라서.. 그분꺼 팬홈피 만드느라 잠수생활이었습니다 ㅠ 
어제가 가수분 생일이셔서 어제 우선 마지막 푸닥거리작업을 마무리하였네요. ㅎ

https://jungyeojin.com/
만들어진 사이트는 위와 같습니다^^(디자인도 제가 다 했습니다. 핫핫)
홈피의 데이터는 오지환님꺼 구글엑셀 파서 가져다가 구글엑셀을 DB처럼 사용하게 해서 만들었네요;;

아무튼 아직 소소한 지인부탁이 조금 남았고,
요즘에는 es6 기초랑 프레임워크없는 개발책도 좀 보고 있긴한데,
슬슬 주말에 조금씩이라도 다시 sapa 좀 볼 수 있을 것같아서 복귀(?) 근황 알려드립니다^^;

**Comment by easylogic** [comment]
우왕 완전 반갑습니다. ^^ 
안그래도 Sapa 에 기능추가를 좀 해볼까 하고 있었는데요. 
딱 맞춰서 와주시네요. ^^ 
저도 최근에 소속을 옮겨서 이것 저것 새롭게 해보고 있습니다. ^^  
천천히 한번 해보시죠. ^^ 


ps. 

사이트 완전 멋져요. ^^
