### ISSUE TITLE
Visual example

### ISSUE THREAD

**Issue by j2l** [easylogic/sapa#35]
Hello!
It's been a long time :)

I think Sapa would need a visual example, something to play with.
Happy to see that you wrote a first sapa example. I tried your example within Codepen:
https://codepen.io/j2l/pen/qBjvPa

Whatever the type of JS from https://cdn.jsdelivr.net/npm/@easylogic/sapa@0.2.4/dist/ I always get an error:
`TypeError: EVENT is not a function `
or `sapa is undefined`

**Comment by easylogic** [comment]
hi @j2l  

you can use v0.3.2.

https://codepen.io/easylogic/pen/MWoxErY

This is very simple example.  

I'll have to make some examples.

**Comment by j2l** [comment]
Ah, great, thanks!
Yes, visual examples would help understand the benefit of your library :)

**Comment by easylogic** [comment]
Thank you for your interest. 
I'll try to make a sample with a storybook.

**Comment by easylogic** [comment]
https://github.com/easylogic/sapa/blob/main/examples/todo.ts 

I added one more simple example. 
Examples will be added here.
